CREATE DATABASE IF NOT EXISTS qt_identity;
CREATE DATABASE IF NOT EXISTS qt_trading;

GRANT ALL PRIVILEGES ON qt_identity.* TO 'qt_app'@'%';
GRANT ALL PRIVILEGES ON qt_trading.* TO 'qt_app'@'%';

FLUSH PRIVILEGES;
